name: Python-Dataviz
conda:
  - gnuplot: 5*
  - bokeh: 1*
  - holoviews: 1.12*
  - hvplot: 0.5*
  - panel: 0.6*
  - voila: 0.1.20*
  - itkwidgets: 0.22*
  - plotly: 4.3*
  - seaborn: 0.9*
  - vincent: 0.4*
  - altair: 3.2*
  - vega_datasets: 0.7*
  - bqplot: 0.11*
  - pythreejs: 2.1*
pip:
  - py4j: 0.10.9
  - beakerx: 1.4.1
labextensions:
  - "@pyviz/jupyterlab_pyviz": 0.8.0
  - jupyterlab_bokeh: 1.0.0
  - "@jupyter-voila/jupyterlab-preview": 0.1.3
  - bqplot: 0.4.9
  - itkwidgets: 0.22.0
  - jupyter-threejs: 2.1.1
  - beakerx-jupyterlab: 1.4.1
